apiVersion: v1
kind: Deployment
metadata:
  name: 'hml'
spec: 
  replicas: 3
  selector: 
    matchLabels:
      app: shakespeare-app
  template:
    metadata:
      labels:
        app: shakespeare-app
    spec:
      containers:
      - name: shakespeare-app
        image: localhost:32000/shakespearepy:v1
        ports: 
        - containerPort: 80
